version: '3.8'

services:
  api1:
    build:
      context: ./api_one
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      API2_URL: http://api2:8081/message 
    restart: on-failure
    networks:
      - app-network

  api2:
    build:
      context: ./api_two
      dockerfile: Dockerfile
    ports:
      - "8081:8081" 
    environment:
      PORT: 8081 
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge